### ISSUE TITLE
Is C source for shims missing?

### ISSUE THREAD

**Issue by adrianboyko** [stefandd/ponystuff#1]
I'm guessing that `sfText_getLocalBounds2` and similar functions are shims? Can you add the C source for the shims to this repository, please?

**Comment by stefandd** [comment]
I uploaded an updated version of the wrapper with the shim lib. I hope it works for you!

**Comment by adrianboyko** [comment]
Thanks! 

FYI, I'm working on 1) adding `vertex_array.pony` and 2) extracting the CSFML stuff into a `pony-csfml` repo / corral bundle.

**Comment by stefandd** [comment]
Cool.
