### ISSUE TITLE
Suggestion: Don't include path information when using a lib.

### ISSUE THREAD

**Issue by adrianboyko** [stefandd/ponystuff#2]
Just a suggestion...  How about making the library "uses" be path-agnostic in core.pony? 

```pony
use "lib:csfml-main"
use "lib:csfml-system"
use "lib:csfml-window"
use "lib:csfml-graphics"
use "lib:csfml-audio"
use "lib:csfmlshim"
```

Then, instead of advising people to edit the source to reflect their particular paths, they can just use `ponyc`'s `-p` option (if they even need to). This makes life simpler for people using systems that install libraries like CSFML into standard locations. For instance, on Linux I just need to specify the path for `csfmlshim` since the rest of the libs (CSFML) install to a standard location for shared libraries.

**Comment by stefandd** [comment]
@adrianboyko I added your suggestions. I also moved this out from being a folder in `ponystuff` to a proper Repo that can be properly forked without all the other *stuff*.
