### ISSUE TITLE
lib:csfml-main is Windows-specific?

### ISSUE THREAD

**Issue by adrianboyko** [stefandd/ponystuff#3]
It looks like use "lib:csfml-main" is Windows-specific. Here are Mac and Linux releases, both of which lack the csfml-main library:
- https://packages.debian.org/source/sid/libcsfml
- https://github.com/SFML/CSFML/releases/download/2.5.1/CSFML-2.5.1-macOS-clang.tar.gz

If you agree that it is Windows-specific, then please add an `if windows` clause to its `use`:
```
use "lib:csfml-main" if windows
```

**Comment by stefandd** [comment]
Good point - added.
